Fix the error reporting to happen in the one place

diff --git a/bin/git-branch-remote b/bin/git-branch-remote
--- a/bin/git-branch-remote
+++ b/bin/git-branch-remote
@@ -4,7 +4,6 @@ if [ "$1" == "" ];then
 	branch=$(git current-branch)
 
 	if [ "$?" -ne "0" ];then
-		echo "Cannot determine current branch" >&2
 		exit 1
 	fi
 else
@@ -14,7 +13,8 @@ fi
 remote=$(git config branch.$branch.remote)
 
 if [ "$remote" == "" ];then
+	echo "Tracking remote could not be determined for $branch" >&2
 	exit 1
-else
-	echo "$remote"
 fi
+
+echo "$remote"
diff --git a/bin/git-current-branch b/bin/git-current-branch
--- a/bin/git-current-branch
+++ b/bin/git-current-branch
@@ -3,6 +3,7 @@
 branch=$(git branch | grep '^\*' | cut -d' ' -f2);
 
 if [ "$branch" == "(HEAD" ];then
+	echo "Cannot determine current branch" >&2
 	exit 1 
 else
 	echo "$branch"
