Add validation on those helper functions

diff --git a/bin/git-_determine-branch b/bin/git-_determine-branch
--- a/bin/git-_determine-branch
+++ b/bin/git-_determine-branch
@@ -2,10 +2,17 @@
 
 branch=$1
 
+git _validate-branch $branch >/dev/null 2>&1
+
+if [[ -n $branch ]] && [[ "$?" -ne "0" ]];then
+	echo "Invalid branch" >&2
+	branch=""
+fi
+
 if [[ -z $branch ]];then
 	branch=$(git current-branch 2>/dev/null)
 
-	if [ "$?" -ne "0" ];then
+	if [[ "$?" -ne "0" ]];then
                 branches=$(git list-branches)
 
 		if [[ $(echo "$branches" | wc -l) == 1 ]];then
diff --git a/bin/git-_determine-remote b/bin/git-_determine-remote
--- a/bin/git-_determine-remote
+++ b/bin/git-_determine-remote
@@ -3,10 +3,17 @@
 remote=$1
 branch=$2
 
+git _validate-remote $remote >/dev/null 2>&1
+
+if [[ -n $remote ]] && [[ "$?" -ne "0" ]];then
+        echo "Invalid remote" >&2
+        remote=""
+fi
+
 if [[ -z $remote ]];then
 	remote=$(git branch-remote "$branch" 2>/dev/null)
 
-	if [ "$?" -ne "0" ];then
+	if [[ "$?" -ne "0" ]];then
                 remotes=$(git remote)
 
 		if [[ $(echo "$remotes" | wc -l) == 1 ]];then
